CREATE TABLE admins(
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(200) NOT NULL,
  salt VARCHAR(200) NOT NULL,
  is_deleted BOOL NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
