CREATE TABLE students(
  id VARCHAR(36) PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(200) NOT NULL,
  salt VARCHAR(200) NOT NULL,
  is_deleted BOOL NOT NULL DEFAULT false,
  last_logined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE student_subscribes(
  id SERIAL PRIMARY KEY,
  student_id VARCHAR(36) NOT NULL,
  school_id INT NOT NULL,
  is_deleted BOOL NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);